version: "3"

services:
  squidproxy:
    image: rafaelsantana6/squid:latest
    hostname: squidproxy
    container_name: squidproxy
    ports:
      - "3128:3128"
    # networks:
    #   - media-network
    environment:
      - UID=1000
      - GID=1000
    volumes:
      - "${CONFIG_FOLDER}/squidproxy/squid.conf:/etc/squid/squid.conf:ro"
      - "${CONFIG_FOLDER}/squidproxy/passwords:/etc/squid/passwords:ro"
      - "${DATA_FOLDER}/squidproxy/logs:/var/log/squid"
      - "${DATA_FOLDER}/squidproxy/cache:/var/spool/squid"
    restart: unless-stopped
# networks:
#   media-network:
#     external: true
