version: "3"

services:
  squidproxy:
    image: rafaelsantana6/squid:latest
    hostname: squidproxy
    container_name: squidproxy
    environment:
      - "UID=1000"
      - "GID=1000"
      - "CONFIG_FOLDER=/mnt/armazenamento/docker/config"
      - "DATA_FOLDER=/mnt/armazenamento/docker/data"
    ports:
      - "3128:3128"
    volumes:
      - "${CONFIG_FOLDER}/squidproxy/squid.conf:/etc/squid/squid.conf:ro"
      - "${CONFIG_FOLDER}/squidproxy/passwords:/etc/squid/passwords:ro"
      - "${DATA_FOLDER}/squidproxy:/var/log/squid"
      - "${DATA_FOLDER}/squidproxy:/var/spool/squid"
    restart: unless-stopped
